#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/cygdrive/d/Projects/hps-nios-fpga/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory_hps', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY_HPS_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY_HPS_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_HPS_COMPONENT_NAME onchip_memory_hps
#define ONCHIP_MEMORY_HPS_BASE 0x0
#define ONCHIP_MEMORY_HPS_SPAN 65536
#define ONCHIP_MEMORY_HPS_END 0xffff
#define ONCHIP_MEMORY_HPS_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_HPS_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_HPS_CONTENTS_INFO ""
#define ONCHIP_MEMORY_HPS_DUAL_PORT 0
#define ONCHIP_MEMORY_HPS_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_HPS_INIT_CONTENTS_FILE soc_system_onchip_memory_hps
#define ONCHIP_MEMORY_HPS_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_HPS_INSTANCE_ID NONE
#define ONCHIP_MEMORY_HPS_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_HPS_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY_HPS_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY_HPS_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_HPS_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_HPS_SIZE_VALUE 65536
#define ONCHIP_MEMORY_HPS_WRITABLE 1
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY_HPS_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory_hps

/*
 * Macros for device 'mailbox_simple_hps2nios', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_SIMPLE_HPS2NIOS_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_SIMPLE_HPS2NIOS_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_SIMPLE_HPS2NIOS_COMPONENT_NAME mailbox_simple_hps2nios
#define MAILBOX_SIMPLE_HPS2NIOS_BASE 0x0
#define MAILBOX_SIMPLE_HPS2NIOS_SPAN 16
#define MAILBOX_SIMPLE_HPS2NIOS_END 0xf

/*
 * Macros for device 'mailbox_simple_nios2hps', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_SIMPLE_NIOS2HPS_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_SIMPLE_NIOS2HPS_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_SIMPLE_NIOS2HPS_COMPONENT_NAME mailbox_simple_nios2hps
#define MAILBOX_SIMPLE_NIOS2HPS_BASE 0x10
#define MAILBOX_SIMPLE_NIOS2HPS_SPAN 16
#define MAILBOX_SIMPLE_NIOS2HPS_END 0x1f
#define MAILBOX_SIMPLE_NIOS2HPS_IRQ 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1513263182

/*
 * Macros for device 'jtag_uart_hps', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_HPS_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_HPS_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_HPS_COMPONENT_NAME jtag_uart_hps
#define JTAG_UART_HPS_BASE 0x20000
#define JTAG_UART_HPS_SPAN 16
#define JTAG_UART_HPS_END 0x2000f
#define JTAG_UART_HPS_IRQ 1
#define JTAG_UART_HPS_READ_DEPTH 64
#define JTAG_UART_HPS_READ_THRESHOLD 8
#define JTAG_UART_HPS_WRITE_DEPTH 64
#define JTAG_UART_HPS_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
