#ifndef NIOS_MAILBOX_H_
#define NIOS_MAILBOX_H_

#define ALTERA_AVALON_MAILBOX_SIMPLE_CMD_OFST          0x0
#define ALTERA_AVALON_MAILBOX_SIMPLE_PTR_OFST          0x1
#define ALTERA_AVALON_MAILBOX_SIMPLE_STS_OFST          0x2
#define ALTERA_AVALON_MAILBOX_SIMPLE_STS_MSK           0x00000003
#define ALTERA_AVALON_MAILBOX_SIMPLE_STS_PENDING_MSK   0x00000001
#define ALTERA_AVALON_MAILBOX_SIMPLE_STS_FULL_MSK      0x00000002
#define ALTERA_AVALON_MAILBOX_SIMPLE_INTR_OFST         0x3
#define ALTERA_AVALON_MAILBOX_SIMPLE_INTR_PEN_MSK      0x00000001
#define ALTERA_AVALON_MAILBOX_SIMPLE_INTR_SPACE_MSK    0x00000002

#define IOC_MAGIC      'h'
#define IOCTL_SET_PID  _IOW(IOC_MAGIC, 1, int)

#define NIOS_MAILBOX_REALTIME_SIGNO  44

#endif /* NIOS_MAILBOX_H_ */
